### PR TITLE
Data Exploration notebook

### PR DESCRIPTION
**Pull request by MadSci356**
Try out the notebook -- Going to use this one for "What is Data Explorer" article. Feel free to update the notebook or let me know if you have suggestions.

Can this notebook be hosted on the website somewhere so in the article, I can put a link to it for download, so people can run it and go through the mini tutorial?

edit: made the article without the notebook. Planning to add reference to the notebook once this "Data Exploration.ipynb" is integrated into the app.

https://support.callistoapp.com/help/what-is-data-explorer

### CODE REVIEW

**Comment by kyle-norris** [comment]
That's great! I like it a lot! Will it need to be hosted online, though? Won't it be part of the app in the `Tutorials` section?

**Comment by MadSci356** [comment]
> That's great! I like it a lot! Will it need to be hosted online, though? Won't it be part of the app in the `Tutorials` section?

Yeah it can be part of Tutorials for sure. I was thinking the "What is Data Explorer" article would have a link to this notebook. So instead explaining how it works it's easy for them to just load up that notebook. Is it easy to host the "tutorial notebooks"? If not, I'll just include screenshots and maybe some sample code.

**Comment by jaylyerly** [comment]
I think this is good.  I made a few suggestions in PR #2.

Main changes

- Use markdown blocks for text instead of python comments
- Use some formatting to make it interesting.
- When describing how to do something, like open the DE, make sure to cover all the options and how they differ on Mac / iPad.

This'll be perfect for the `Features` section on the welcome screen.

**Comment by MadSci356** [comment]
@jaylyerly  is this good to merge now?

**Comment by jaylyerly** [comment]
> @jaylyerly is this good to merge now?

👍

**Review by jaylyerly — APPROVED** [review]

**Pull request merged**
